[package]
name = "rust_gpt"
version = "0.1.0"
edition = "2021"

[dependencies]
async-openai = "0.28.1"
rig-core = "0.12.0"
schemars = "0.8.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["full"] }
